language: php

php:
  - "5.4"
  - "5.3"

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php -l
  - phpcs --report=checkstyle --standard=Zend . 
script:
  phpunit tests/AllTests.php --coverage-text