language: php

php:
  - "5.4"
  - "5.3"

before_script:
  - pear install pear/PHP_CodeSniffer
  - pear channel-discover pear.bovigo.org
  - pear install bovigo/vfsStream-beta
  - phpenv rehash
  - phpcs --report=checkstyle --standard=Zend .
script:
  phpunit -v --colors tests/AllTests.php --coverage-text
